package expo.modules.opagowalletcrypto;

import static org.junit.Assert.*;
import org.junit.Test;
import java.security.GeneralSecurityException;

public class Bip39SeedTest {
  @Test public void matchesExistingBip39ForEverySupportedWordCount() throws Exception {
    // Public, synthetic fixtures independently generated by bip39 3.1.0.
    String[][] vectors = {
      {"abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about", "5eb00bbddcf069084889a8ab9155568165f5c453ccb85e70811aaed6f6da5fc19a5ac40b389cd370d086206dec8aa6c43daea6690f20ad3d8d48b2d2ce9e38e4"},
      {"drastic bamboo mountain loyal category cancel animal embark drastic bamboo mountain lunch", "11bcc5993e9f3be47884542b17e7e6bd698edbb36a02c5a3bf521a0eb5d5afb2c71d0b7d3d0e5eb738128ae355e4da9c05ed8683735b99e768cc828b54dd32af"},
      {"drastic bamboo mountain loyal category cancel animal embark drastic bamboo mountain loyal category cancel apart", "7b5ddbbf0732248035786a2c2000ad71fbe74ec173fe0c4030658d6fac1f6108a9aed62e441e07f1a95332778768a2949d894e6ff957f85872c64c34722d01b9"},
      {"drastic bamboo mountain loyal category cancel animal embark drastic bamboo mountain loyal category cancel animal embark drastic birth", "a92d3f389b1de4d9fbc921bb7aa428c150a6d7b0a0c9993f7705e08fbaf6643c67974889ebb0d81603449c985f3f06f52d03f384b7b0f9f32873224c7f40373c"},
      {"drastic bamboo mountain loyal category cancel animal embark drastic bamboo mountain loyal category cancel animal embark drastic bamboo mountain loyal change", "e5974f5a623dab3daa762014832a31a2b75131d36fd9f4a8b2faa2ecad5fa87bb4f9d60bf4ddf7d0f81d9f17021a6a31cd34a8f53fde3963ccba2a903d187a15"},
      {"drastic bamboo mountain loyal category cancel animal embark drastic bamboo mountain loyal category cancel animal embark drastic bamboo mountain loyal category cancel animal embark", "28ff2a1e69973dc780cd89f74f7ab2145dce35d30b116a6e5fc69fd55ee30a8fda29d5c288f24f7af2146cc12c7c89852e75d0d82d3f0a34ef25473383d56fba"},
    };
    for (String[] vector : vectors) {
      byte[] actual = Bip39Seed.derive(vector[0]);
      assertEquals(64, actual.length);
      StringBuilder hex = new StringBuilder();
      for (byte value : actual) hex.append(String.format("%02x", value & 0xff));
      assertEquals(vector[1], hex.toString());
    }
  }

  @Test public void rejectsNoncanonicalInputsWithoutEchoingThem() {
    String[] invalid = {null, "", "private example", "abandon ".repeat(12), "ABANDON ".repeat(11) + "ABOUT", "é ".repeat(11) + "é", "a ".repeat(24) + "a"};
    for (String input : invalid) {
      GeneralSecurityException error = assertThrows(GeneralSecurityException.class, () -> Bip39Seed.derive(input));
      assertEquals("Invalid recovery phrase format.", error.getMessage());
    }
  }
}
