import { StyleSheet } from 'react-native';
import { adaptiveStyles } from '@/lib/theme-styles';

// Camera imagery uses a dark scrim in both app modes. The manual-entry sheet
// below it follows the selected app palette.
export const scannerDarkStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#09090b' },
  screenContent: { flex: 1 },
  page: { flexGrow: 1, paddingHorizontal: 22 },
  header: { flexDirection: 'row', alignItems: 'center', gap: 16 },
  title: { flex: 1, fontSize: 24, lineHeight: 30, fontWeight: '600', letterSpacing: -0.7, color: '#f9f9fa' },
  circle: { width: 44, height: 44, borderRadius: 22, backgroundColor: 'rgba(37,37,39,0.82)', borderWidth: 1, borderColor: '#ffffff14', alignItems: 'center', justifyContent: 'center' },
  prompt: { color: '#d0cfd1', fontSize: 14, lineHeight: 21, textAlign: 'center', marginTop: 30, marginBottom: 24 },
  stage: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingVertical: 15 },
  corner: { position: 'absolute', width: 38, height: 38 },
  topLeft: { top: 0, left: 0, borderTopWidth: 2.5, borderLeftWidth: 2.5, borderTopLeftRadius: 27 },
  topRight: { top: 0, right: 0, borderTopWidth: 2.5, borderRightWidth: 2.5, borderTopRightRadius: 27 },
  bottomLeft: { bottom: 0, left: 0, borderBottomWidth: 2.5, borderLeftWidth: 2.5, borderBottomLeftRadius: 27 },
  bottomRight: { bottom: 0, right: 0, borderBottomWidth: 2.5, borderRightWidth: 2.5, borderBottomRightRadius: 27 },
  flash: { marginTop: 32 }, flashOn: { backgroundColor: '#ffb000', borderColor: '#ffb000' },
  finderStatus: { ...StyleSheet.absoluteFillObject, borderRadius: 27, backgroundColor: '#09090b91', alignItems: 'center', justifyContent: 'center', gap: 14 },
  check: { width: 48, height: 48, borderRadius: 24, backgroundColor: '#8de4bd', alignItems: 'center', justifyContent: 'center' },
  foundText: { color: '#fff', fontSize: 14, lineHeight: 21, fontWeight: '600', textAlign: 'center' },
  cameraMessage: { alignItems: 'center', gap: 18, paddingVertical: 20, paddingHorizontal: 12 },
  message: { color: '#d4d4da', fontSize: 15, lineHeight: 23, textAlign: 'center' },
  permissionButton: { minHeight: 48, paddingHorizontal: 18, paddingVertical: 12, backgroundColor: '#ffb000', borderRadius: 16 },
  permissionText: { color: '#141008', fontSize: 15, fontWeight: '600', textAlign: 'center' },
  bottom: { paddingTop: 24 },
  dock: { flexDirection: 'row', alignItems: 'stretch', padding: 7, backgroundColor: 'rgba(32,32,34,0.92)', borderWidth: 1, borderColor: '#ffffff13', borderRadius: 20 },
  dockStack: { flexDirection: 'column' },
  dockButton: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 9, minHeight: 51, paddingVertical: 10, paddingHorizontal: 5 },
  dockText: { color: '#f7f7f7', fontSize: 14, lineHeight: 20, fontWeight: '600', flexShrink: 1 },
  divider: { width: 1, backgroundColor: '#ffffff13', marginVertical: 6 },
  dividerHorizontal: { height: 1, backgroundColor: '#ffffff13', marginHorizontal: 8 },
  trust: { fontSize: 12, lineHeight: 18, color: '#b7b7c0', textAlign: 'center', marginTop: 19 },
  errorBox: { alignSelf: 'stretch', backgroundColor: '#151517ed', borderRadius: 20, padding: 16, marginTop: 16 },
  error: { color: '#ffc1ac', fontSize: 14, lineHeight: 21, marginBottom: 12 },
  modalRoot: { flex: 1, justifyContent: 'flex-end' },
  sheet: { flexShrink: 1, backgroundColor: '#171719', borderTopColor: '#ffffff1c', borderTopWidth: 1, borderTopLeftRadius: 29, borderTopRightRadius: 29, paddingTop: 12 },
  handle: { width: 32, height: 4, borderRadius: 3, backgroundColor: '#505053', alignSelf: 'center', marginBottom: 20 },
  sheetContent: { paddingHorizontal: 23, paddingBottom: 4 },
  sheetHeader: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 18 },
  sheetTitle: { flex: 1, fontSize: 25, lineHeight: 31, fontWeight: '600', letterSpacing: -0.6, color: '#f9f9fa' },
  eyebrow: { flex: 1, fontSize: 14, lineHeight: 21, color: '#b6b6be' },
  sheetDescription: { color: '#b7b7be', fontSize: 14, lineHeight: 22 },
  label: { color: '#c3c3ca', fontSize: 13, lineHeight: 20, marginTop: 22, marginBottom: 9 },
  input: { backgroundColor: '#202023', borderWidth: 1, borderColor: '#54545e', borderRadius: 16, color: '#f8f8fa', fontSize: 16, lineHeight: 24, padding: 16, minHeight: 64, maxHeight: 140, textAlignVertical: 'top', marginBottom: 18 },
  primary: { minHeight: 54, padding: 15, borderRadius: 16, backgroundColor: '#ffb000', flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 10 },
  primaryText: { fontSize: 16, lineHeight: 22, fontWeight: '600', textAlign: 'center', color: '#141008', flexShrink: 1 },
  secondary: { minHeight: 48, padding: 12, alignItems: 'center', justifyContent: 'center', marginTop: 6 },
  secondaryText: { color: '#ceced4', fontSize: 14, lineHeight: 21, textAlign: 'center' },
  disabled: { opacity: 0.45 },
  recipient: { flexDirection: 'row', alignItems: 'flex-start', gap: 12, marginBottom: 20 },
  recipientIcon: { width: 44, height: 44, backgroundColor: '#262629', borderRadius: 15, alignItems: 'center', justifyContent: 'center' },
  recipientCopy: { flex: 1, gap: 5 },
  recipientTitle: { fontSize: 15, lineHeight: 22, fontWeight: '600', color: '#f7f7fa' },
  recipientValue: { fontSize: 12, lineHeight: 18, color: '#b3b3bb' },
  amount: { fontSize: 27, lineHeight: 34, color: '#f9f9fa', fontWeight: '600', letterSpacing: -0.6, marginBottom: 22 },
});

export const scannerStyles = adaptiveStyles(scannerDarkStyles);
