import { StyleSheet } from 'react-native';

export const sendStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0a0a0c',
    paddingHorizontal: 16,
    paddingTop: 52,
  },
  centered: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  title: { color: '#fff', fontSize: 30, fontWeight: '800' },
  subtitle: { color: '#8f8f9d', fontSize: 15, lineHeight: 22 },
  banner: {
    backgroundColor: 'rgba(107,92,195,0.14)',
    borderColor: 'rgba(107,92,195,0.5)',
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    marginBottom: 16,
  },
  bannerText: { color: '#c9c0ff', fontSize: 13, textAlign: 'center' },
  testnetBanner: {
    backgroundColor: 'rgba(255,176,0,0.14)',
    borderColor: '#ffb000',
    borderWidth: 2,
    borderRadius: 12,
    padding: 14,
    marginBottom: 16,
    alignItems: 'center',
  },
  testnetTitle: { color: '#ffb000', fontSize: 18, fontWeight: '900', letterSpacing: 2 },
  testnetText: { color: '#ffe2a3', fontSize: 12, marginTop: 4, textAlign: 'center' },
  card: {
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderColor: 'rgba(255,255,255,0.09)',
    borderWidth: 1,
    borderRadius: 20,
    padding: 18,
  },
  label: {
    color: '#a0a0ab',
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 8,
  },
  input: {
    backgroundColor: '#17171c',
    borderColor: '#2d2d35',
    borderWidth: 1,
    borderRadius: 12,
    color: '#fff',
    padding: 14,
    minHeight: 54,
    marginBottom: 16,
  },
  destinationInput: { height: 88, textAlignVertical: 'top' },
  row: { flexDirection: 'row', gap: 8 },
  selector: {
    flex: 1,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#33333d',
    paddingVertical: 11,
    alignItems: 'center',
    marginBottom: 16,
  },
  selectorActive: { borderColor: '#ffb000', backgroundColor: 'rgba(255,176,0,0.12)' },
  selectorText: { color: '#8f8f9d', fontWeight: '700' },
  selectorTextActive: { color: '#ffb000' },
  button: {
    backgroundColor: '#ffb000',
    minHeight: 54,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  secondaryButton: {
    backgroundColor: 'transparent',
    borderColor: '#3c3c46',
    borderWidth: 1,
    marginTop: 12,
  },
  buttonText: { color: '#111', fontSize: 16, fontWeight: '800' },
  secondaryButtonText: { color: '#fff' },
  scanButton: {
    paddingHorizontal: 14,
    minHeight: 44,
    borderRadius: 12,
    backgroundColor: 'rgba(255,176,0,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  scanText: { color: '#ffb000', fontWeight: '800' },
  successCircle: {
    width: 92,
    height: 92,
    borderRadius: 46,
    backgroundColor: 'rgba(73,209,125,0.16)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 24,
  },
  checkmark: { color: '#49d17d', fontSize: 48, fontWeight: '800' },
  successTitle: { color: '#fff', fontSize: 28, fontWeight: '800', marginBottom: 10 },
  proofBox: {
    width: '100%',
    backgroundColor: '#17171c',
    borderRadius: 12,
    padding: 14,
    marginVertical: 24,
  },
  proofText: { color: '#a0a0ab', fontFamily: 'monospace', textAlign: 'center' },
  quoteTitle: { color: '#fff', fontSize: 26, fontWeight: '800', marginBottom: 8 },
  quoteBox: {
    width: '100%',
    backgroundColor: '#17171c',
    borderRadius: 16,
    padding: 18,
    marginVertical: 24,
  },
  quoteRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 8,
  },
  quoteLabel: { color: '#8f8f9d' },
  quoteValue: { color: '#fff', fontWeight: '700' },
  option: {
    borderColor: '#33333d',
    borderWidth: 1,
    borderRadius: 14,
    padding: 15,
    marginBottom: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  optionActive: { borderColor: '#ffb000', backgroundColor: 'rgba(255,176,0,0.09)' },
  optionTitle: { color: '#fff', fontWeight: '800', fontSize: 16 },
  optionMeta: { color: '#8f8f9d', marginTop: 4 },
  camera: { flex: 1, backgroundColor: '#000' },
  cameraClose: {
    position: 'absolute',
    top: 50,
    right: 20,
    backgroundColor: 'rgba(0,0,0,0.7)',
    borderRadius: 20,
    padding: 12,
  },
  cameraCloseText: { color: '#fff', fontWeight: '700' },
  errorText: { color: '#ff6666', marginTop: 12, textAlign: 'center' },
});
