import { StyleSheet } from 'react-native';

export const sendStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0a0a0c',
    paddingHorizontal: 16,
    paddingTop: 52,
  },
  scrollContainer: { flex: 1, backgroundColor: '#0a0a0c' },
  formContent: {
    flexGrow: 1,
    paddingHorizontal: 16,
    paddingTop: 56,
    paddingBottom: 36,
  },
  centered: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    marginBottom: 20,
  },
  centerText: { textAlign: 'center' },
  backButton: { alignSelf: 'flex-start', flexDirection: 'row', alignItems: 'center', gap: 9, minHeight: 48, paddingRight: 16, marginBottom: 8 },
  backButtonText: { color: '#fff', fontSize: 15, fontWeight: '500' },
  title: { color: '#fff', fontSize: 28, fontWeight: '800' },
  screenSubtitle: { color: '#8f8f9d', fontSize: 13, marginTop: 4 },
  subtitle: { color: '#8f8f9d', fontSize: 15, lineHeight: 22 },
  banner: {
    backgroundColor: 'rgba(107,92,195,0.14)',
    borderColor: 'rgba(107,92,195,0.5)',
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    marginBottom: 16,
  },
  bannerText: { color: '#c9c0ff', fontSize: 13, textAlign: 'center' },
  modeNotice: {
    backgroundColor: '#121216',
    borderRadius: 16,
    padding: 13,
    marginBottom: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
  },
  modeNoticeIcon: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: 'rgba(107,92,195,0.16)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modeNoticeIconLive: { backgroundColor: 'rgba(73,209,125,0.12)' },
  modeNoticeCopy: { flex: 1 },
  modeNoticeTitle: { color: '#fff', fontSize: 13, fontWeight: '800' },
  modeNoticeText: { color: '#81818d', fontSize: 11, marginTop: 2 },
  testnetBanner: {
    backgroundColor: 'rgba(255,176,0,0.14)',
    borderColor: '#ffb000',
    borderWidth: 2,
    borderRadius: 12,
    padding: 14,
    marginBottom: 16,
    alignItems: 'center',
  },
  testnetTitle: { color: '#ffb000', fontSize: 18, fontWeight: '900', letterSpacing: 2 },
  testnetText: { color: '#ffe2a3', fontSize: 12, marginTop: 4, textAlign: 'center' },
  testnetBannerContent: { flexDirection: 'row', alignItems: 'center', gap: 11 },
  networkPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    backgroundColor: '#17171c',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 7,
    marginBottom: 24,
  },
  networkPillText: { color: '#b8b8c2', fontSize: 11, fontWeight: '800' },
  card: {
    backgroundColor: '#121216',
    borderColor: 'rgba(255,255,255,0.09)',
    borderWidth: 1,
    borderRadius: 22,
    padding: 18,
  },
  label: {
    color: '#d3d3da',
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 8,
  },
  input: {
    backgroundColor: '#17171c',
    borderColor: '#2d2d35',
    borderWidth: 1,
    borderRadius: 12,
    color: '#fff',
    padding: 14,
    minHeight: 54,
    marginBottom: 16,
  },
  destinationInput: { minHeight: 72, maxHeight: 96, textAlignVertical: 'top' },
  amountGuidance: { marginBottom: 12, gap: 5 },
  amountGuidanceTitle: { color: '#ffb000', fontSize: 14, lineHeight: 20 },
  amountGuidanceText: { color: '#a5a5b1', fontSize: 13, lineHeight: 19 },
  row: { flexDirection: 'row', gap: 8 },
  selector: {
    flex: 1,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#33333d',
    paddingVertical: 11,
    alignItems: 'center',
    marginBottom: 16,
  },
  selectorActive: { borderColor: '#ffb000', backgroundColor: 'rgba(255,176,0,0.12)' },
  selectorText: { color: '#8f8f9d', fontWeight: '700' },
  selectorTextActive: { color: '#ffb000' },
  receiveNetworkRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 16 },
  receiveNetworkSelector: {
    flexBasis: '47%',
    flexGrow: 1,
    minHeight: 105,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#33333d',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
    paddingVertical: 10,
  },
  receiveNetworkText: { color: '#fff', fontWeight: '800', fontSize: 12, marginTop: 7 },
  receiveNetworkMeta: { color: '#666673', fontWeight: '900', fontSize: 8, letterSpacing: 0.5, marginTop: 3 },
  assetGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 16,
  },
  assetSelector: {
    flexBasis: '47%',
    flexGrow: 1,
    minHeight: 116,
    backgroundColor: '#17171c',
    borderColor: '#2d2d35',
    borderWidth: 1,
    borderRadius: 14,
    padding: 12,
  },
  assetSelectorActive: {
    borderColor: '#ffb000',
    backgroundColor: 'rgba(255,176,0,0.08)',
  },
  assetSelectorHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 9,
  },
  assetSelectorTitle: { color: '#fff', fontWeight: '800', fontSize: 14 },
  assetSelectorBalance: { color: '#a0a0ab', fontSize: 11, marginTop: 4 },
  assetSelectorMeta: { color: '#666673', fontSize: 9, fontWeight: '900', letterSpacing: 0.7, marginTop: 5 },
  primaryChoiceButton: { minHeight: 64 },
  choiceDivider: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginVertical: 20,
  },
  choiceDividerLine: { flex: 1, height: 1, backgroundColor: '#2a2a31' },
  choiceDividerText: { color: '#787884', fontSize: 12, fontWeight: '700', flexShrink: 1, textAlign: 'center' },
  choiceTitle: { color: '#fff', fontSize: 18, fontWeight: '800', marginBottom: 16 },
  selectedAssetRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#17171c',
    borderRadius: 14,
    padding: 13,
    marginBottom: 22,
  },
  selectedAssetCopy: { flex: 1, marginLeft: 12 },
  selectedAssetTitle: { color: '#fff', fontSize: 16, fontWeight: '800' },
  selectedAssetMeta: { color: '#8f8f9d', fontSize: 11, marginTop: 3 },
  changeAssetButton: {
    minHeight: 40,
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  changeAssetText: { color: '#ffb000', fontSize: 13, fontWeight: '800' },
  button: {
    backgroundColor: '#ffb000',
    minHeight: 54,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  buttonDisabled: { opacity: 0.45 },
  fullWidthButton: { width: '100%' },
  secondaryButton: {
    backgroundColor: 'transparent',
    borderColor: '#3c3c46',
    borderWidth: 1,
    marginTop: 12,
  },
  buttonText: { color: '#111', fontSize: 16, fontWeight: '800', flexShrink: 1, textAlign: 'center' },
  buttonContent: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 },
  secondaryButtonText: { color: '#fff' },
  currencyToggle: { minHeight: 46, marginTop: 0 },
  scanButton: {
    paddingHorizontal: 14,
    minHeight: 44,
    borderRadius: 12,
    backgroundColor: 'rgba(255,176,0,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  scanText: { color: '#ffb000', fontWeight: '800' },
  successCircle: {
    width: 92,
    height: 92,
    borderRadius: 46,
    backgroundColor: 'rgba(73,209,125,0.16)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 24,
  },
  checkmark: { color: '#49d17d', fontSize: 48, fontWeight: '800' },
  successTitle: { color: '#fff', fontSize: 28, fontWeight: '800', marginBottom: 8 },
  successAmount: { color: '#fff', fontSize: 36, fontWeight: '800', marginBottom: 10 },
  successSummary: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    backgroundColor: 'rgba(73,209,125,0.1)',
    borderRadius: 999,
    paddingHorizontal: 13,
    paddingVertical: 8,
    marginVertical: 22,
  },
  successSummaryText: { color: '#91dbaa', fontSize: 12, fontWeight: '700' },
  proofBox: {
    width: '100%',
    backgroundColor: '#17171c',
    borderRadius: 12,
    padding: 14,
    marginVertical: 24,
  },
  proofText: { color: '#a0a0ab', fontFamily: 'monospace', textAlign: 'center' },
  accountDisplay: { color: '#fff', fontSize: 17, fontWeight: '700', textAlign: 'center' },
  copyHint: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 6, marginTop: 8 },
  copyHintText: { color: '#8f8f9d', fontSize: 12, fontWeight: '700' },
  qrSection: { alignItems: 'center', marginTop: 18 },
  qrCard: {
    backgroundColor: '#fff',
    padding: 16,
    borderRadius: 18,
    borderColor: 'rgba(255,255,255,0.14)',
    borderWidth: 1,
  },
  paymentEyebrow: {
    color: '#8f8f9d',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.2,
    marginTop: 18,
  },
  amountHero: { color: '#fff', fontSize: 38, fontWeight: '800', marginTop: 6, marginBottom: 6 },
  quoteTitle: { color: '#fff', fontSize: 26, fontWeight: '800', marginBottom: 8 },
  quoteBox: {
    width: '100%',
    backgroundColor: '#17171c',
    borderRadius: 16,
    padding: 18,
    marginVertical: 24,
  },
  quoteRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 8,
  },
  quoteLabel: { color: '#8f8f9d', flexShrink: 1, maxWidth: '55%' },
  quoteValue: {
    color: '#fff',
    fontWeight: '700',
    flexShrink: 1,
    maxWidth: '68%',
    marginLeft: 12,
    textAlign: 'right',
  },
  safetyNote: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    backgroundColor: 'rgba(242,180,93,0.08)',
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
  },
  safetyText: { color: '#c3a06d', flex: 1, fontSize: 12, lineHeight: 17 },
  detailsToggle: {
    width: '100%',
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    marginBottom: 12,
  },
  detailsToggleText: { color: '#9b9ba7', fontSize: 13, fontWeight: '700' },
  technicalDetails: {
    width: '100%',
    backgroundColor: '#121216',
    borderRadius: 14,
    padding: 15,
    marginBottom: 18,
  },
  detailsLabel: { marginTop: 18 },
  textButton: { minHeight: 48, alignItems: 'center', justifyContent: 'center', marginTop: 6 },
  textButtonText: { color: '#a0a0ab', fontSize: 14, fontWeight: '700' },
  option: {
    borderColor: '#33333d',
    borderWidth: 1,
    borderRadius: 14,
    padding: 15,
    marginBottom: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  optionIdentity: { flexDirection: 'row', alignItems: 'center', gap: 11 },
  optionActive: { borderColor: '#ffb000', backgroundColor: 'rgba(255,176,0,0.09)' },
  optionTitle: { color: '#fff', fontWeight: '800', fontSize: 16 },
  optionMeta: { color: '#8f8f9d', marginTop: 4 },
  camera: { flex: 1, backgroundColor: '#000' },
  cameraHeader: {
    position: 'absolute',
    top: 72,
    left: 24,
    right: 24,
    alignItems: 'center',
  },
  cameraTitle: { color: '#fff', fontSize: 24, fontWeight: '800' },
  cameraSubtitle: { color: 'rgba(255,255,255,0.76)', fontSize: 13, marginTop: 6 },
  scannerFrame: {
    position: 'absolute',
    width: 246,
    height: 246,
    borderRadius: 28,
    borderWidth: 3,
    borderColor: '#ffb000',
    top: '30%',
    alignSelf: 'center',
  },
  cameraClose: {
    position: 'absolute',
    top: 50,
    right: 20,
    backgroundColor: 'rgba(0,0,0,0.7)',
    borderRadius: 20,
    padding: 12,
  },
  cameraCloseText: { color: '#fff', fontWeight: '700' },
  errorText: { color: '#ff6666', marginTop: 12, textAlign: 'center' },
});
